# manufacturer_config_JM.py
# Updated on: 2026-02-21 01:32:03
# Filtered from JACars listings: models present in actual listings only

# Vehicle categories based on Jamaica's importation age limits effective November 6, 2019
# Categories: motorcycles_atvs(5), cars(6), light_commercial(6-10), commercial(12-30), heavy_duty(30)


manufacturer_configs = {
    "ACURA": {
        "MDX": {"category": "cars", "age_limit": 10},
        "RDX": {"category": "cars", "age_limit": 10},
        "RSX": {"category": "cars", "age_limit": 10},
        "TL": {"category": "cars", "age_limit": 10}
    },
    "AUDI": {
        "A3": {"category": "cars", "age_limit": 10},
        "A4": {"category": "cars", "age_limit": 10},
        "A5": {"category": "cars", "age_limit": 10},
        "A6": {"category": "cars", "age_limit": 10},
        "A7": {"category": "cars", "age_limit": 10},
        "Q2": {"category": "cars", "age_limit": 10},
        "Q3": {"category": "cars", "age_limit": 10},
        "Q5": {"category": "cars", "age_limit": 10},
        "Q7": {"category": "cars", "age_limit": 10},
        "Q8": {"category": "cars", "age_limit": 10},
        "S3": {"category": "cars", "age_limit": 10},
        "SQ5": {"category": "cars", "age_limit": 10},
        "TT": {"category": "cars", "age_limit": 10}
    },
    "BMW": {
        "1 SERIES": {"category": "cars", "age_limit": 10},
        "2 SERIES": {"category": "cars", "age_limit": 10},
        "3 SERIES": {"category": "cars", "age_limit": 10},
        "4 SERIES": {"category": "cars", "age_limit": 10},
        "5 SERIES": {"category": "cars", "age_limit": 10},
        "6 SERIES": {"category": "cars", "age_limit": 10},
        "7 SERIES": {"category": "cars", "age_limit": 10},
        "M2": {"category": "cars", "age_limit": 10},
        "M3": {"category": "cars", "age_limit": 10},
        "M4": {"category": "cars", "age_limit": 10},
        "X1": {"category": "cars", "age_limit": 10},
        "X2": {"category": "cars", "age_limit": 10},
        "X3": {"category": "cars", "age_limit": 10},
        "X4": {"category": "cars", "age_limit": 10},
        "X5": {"category": "cars", "age_limit": 10},
        "X6": {"category": "cars", "age_limit": 10},
        "XM": {"category": "cars", "age_limit": 10}
    },
    "CADILLAC": {
        "CTS": {"category": "cars", "age_limit": 10}
    },
    "CHEVROLET": {
        "CRUZE": {"category": "cars", "age_limit": 10},
        "MALIBU": {"category": "cars", "age_limit": 10},
        "SUBURBAN": {"category": "cars", "age_limit": 10}
    },
    "DAIHATSU": {
        "BOON": {"category": "cars", "age_limit": 10},
        "HIJET": {"category": "light_commercial", "age_limit": 6},
        "MIRA": {"category": "cars", "age_limit": 10},
        "ROCKY": {"category": "cars", "age_limit": 10}
    },
    "DODGE": {
        "RAM": {"category": "cars", "age_limit": 10}
    },
    "FORD": {
        "BRONCO": {"category": "cars", "age_limit": 10},
        "ESCAPE": {"category": "cars", "age_limit": 10},
        "EXPLORER": {"category": "cars", "age_limit": 10},
        "F150": {"category": "light_commercial", "age_limit": 6}
    },
    "HONDA": {
        "ACCORD": {"category": "cars", "age_limit": 10},
        "AIRWAVE": {"category": "cars", "age_limit": 10},
        "CITY": {"category": "cars", "age_limit": 10},
        "CIVIC": {"category": "cars", "age_limit": 10},
        "CR-V": {"category": "cars", "age_limit": 10},
        "ELYSION": {"category": "cars", "age_limit": 10},
        "FIT": {"category": "cars", "age_limit": 10},
        "FIT ARIA": {"category": "cars", "age_limit": 10},
        "FIT SHUTTLE": {"category": "cars", "age_limit": 10},
        "FREED": {"category": "cars", "age_limit": 10},
        "GRACE": {"category": "cars", "age_limit": 10},
        "HR-V": {"category": "cars", "age_limit": 10},
        "INSIGHT": {"category": "cars", "age_limit": 10},
        "INSPIRE": {"category": "cars", "age_limit": 10},
        "INTEGRA": {"category": "cars", "age_limit": 10},
        "JADE": {"category": "cars", "age_limit": 10},
        "JAZZ": {"category": "cars", "age_limit": 10},
        "MOBILIO": {"category": "cars", "age_limit": 10},
        "N-WGN": {"category": "cars", "age_limit": 10},
        "ODYSSEY": {"category": "cars", "age_limit": 10},
        "PILOT": {"category": "cars", "age_limit": 10},
        "RIDGELINE": {"category": "cars", "age_limit": 10},
        "SHUTTLE": {"category": "cars", "age_limit": 10},
        "STEPWGN": {"category": "cars", "age_limit": 10},
        "STEPWGN SPADA": {"category": "cars", "age_limit": 10},
        "STREAM": {"category": "cars", "age_limit": 10},
        "TORNEO": {"category": "cars", "age_limit": 10},
        "VEZEL": {"category": "cars", "age_limit": 10},
        "ZR-V": {"category": "cars", "age_limit": 10}
    },
    "HYUNDAI": {
        "ACCENT": {"category": "cars", "age_limit": 10},
        "SANTA FE": {"category": "cars", "age_limit": 10},
        "TUCSON": {"category": "cars", "age_limit": 10}
    },
    "ISUZU": {
        "ELF TRUCK": {"category": "cars", "age_limit": 10},
        "TROOPER": {"category": "cars", "age_limit": 10},
        "TRUCK": {"category": "cars", "age_limit": 10}
    },
    "JAGUAR": {
        "E-PACE": {"category": "cars", "age_limit": 10},
        "F-PACE": {"category": "cars", "age_limit": 10},
        "XE": {"category": "cars", "age_limit": 10},
        "XF": {"category": "cars", "age_limit": 10},
        "XJS": {"category": "cars", "age_limit": 10}
    },
    "JEEP": {
        "COMPASS": {"category": "cars", "age_limit": 10},
        "GRAND CHEROKEE": {"category": "cars", "age_limit": 10},
        "RENEGADE": {"category": "cars", "age_limit": 10},
        "WRANGLER": {"category": "cars", "age_limit": 10},
        "WRANGLER UNLIMITED": {"category": "cars", "age_limit": 10}
    },
    "LAND ROVER": {
        "DISCOVERY": {"category": "cars", "age_limit": 10},
        "RANGE ROVER": {"category": "cars", "age_limit": 10},
        "RANGE ROVER EVOQUE": {"category": "cars", "age_limit": 10},
        "RANGE ROVER SPORT": {"category": "cars", "age_limit": 10},
        "RANGE ROVER VELAR": {"category": "cars", "age_limit": 10}
    },
    "LEXUS": {
        "GS": {"category": "cars", "age_limit": 10},
        "IS": {"category": "cars", "age_limit": 10},
        "NX": {"category": "cars", "age_limit": 10},
        "RX": {"category": "cars", "age_limit": 10}
    },
    "MAZDA": {
        "ATENZA": {"category": "cars", "age_limit": 10},
        "AXELA": {"category": "cars", "age_limit": 10},
        "BIANTE": {"category": "cars", "age_limit": 10},
        "BONGO": {"category": "light_commercial", "age_limit": 10},
        "CX-3": {"category": "cars", "age_limit": 10},
        "CX-30": {"category": "cars", "age_limit": 10},
        "CX-5": {"category": "cars", "age_limit": 10},
        "CX-8": {"category": "cars", "age_limit": 10},
        "CX-9": {"category": "cars", "age_limit": 10},
        "DEMIO": {"category": "cars", "age_limit": 10},
        "FAMILIA": {"category": "cars", "age_limit": 10},
        "MAZDA3": {"category": "cars", "age_limit": 10},
        "MAZDA6": {"category": "cars", "age_limit": 10},
        "MPV": {"category": "cars", "age_limit": 10},
        "PREMACY": {"category": "cars", "age_limit": 10},
        "TITAN": {"category": "commercial", "age_limit": 20}
    },
    "MERCEDES BENZ": {
        "A CLASS": {"category": "cars", "age_limit": 10},
        "AMG": {"category": "cars", "age_limit": 10},
        "AMG G CLASS": {"category": "cars", "age_limit": 10},
        "AMG GT": {"category": "cars", "age_limit": 10},
        "B CLASS": {"category": "cars", "age_limit": 10},
        "C CLASS": {"category": "cars", "age_limit": 10},
        "CLA": {"category": "cars", "age_limit": 10},
        "CLS CLASS": {"category": "cars", "age_limit": 10},
        "E CLASS": {"category": "cars", "age_limit": 10},
        "G CLASS": {"category": "cars", "age_limit": 10},
        "GLA": {"category": "cars", "age_limit": 10},
        "GLC": {"category": "cars", "age_limit": 10},
        "GLE": {"category": "cars", "age_limit": 10},
        "GLS": {"category": "cars", "age_limit": 10},
        "M CLASS": {"category": "cars", "age_limit": 10},
        "S CLASS": {"category": "cars", "age_limit": 10},
        "SL": {"category": "cars", "age_limit": 10}
    },
    "MINI": {
        "MINI": {"category": "cars", "age_limit": 10},
        "MINI CLUBMAN": {"category": "cars", "age_limit": 10},
        "MINI CONVERTIBLE": {"category": "cars", "age_limit": 10},
        "MINI COOPER": {"category": "cars", "age_limit": 10}
    },
    "MITSUBISHI": {
        "AIRTREK": {"category": "cars", "age_limit": 10},
        "CANTER": {"category": "commercial", "age_limit": 20},
        "COLT": {"category": "cars", "age_limit": 10},
        "GALANT FORTIS": {"category": "cars", "age_limit": 10},
        "GRANDIS": {"category": "cars", "age_limit": 10},
        "I": {"category": "cars", "age_limit": 10},
        "LANCER": {"category": "cars", "age_limit": 10},
        "LANCER EVOLUTION": {"category": "cars", "age_limit": 10},
        "MIRAGE": {"category": "cars", "age_limit": 10},
        "MONTERO": {"category": "cars", "age_limit": 10},
        "PAJERO": {"category": "cars", "age_limit": 10},
        "RVR": {"category": "cars", "age_limit": 10}
    },
    "NISSAN": {
        "AD EXPERT": {"category": "light_commercial", "age_limit": 10},
        "AD WAGON": {"category": "cars", "age_limit": 10},
        "ALTIMA": {"category": "cars", "age_limit": 10},
        "BLUEBIRD": {"category": "cars", "age_limit": 10},
        "BLUEBIRD SYLPHY": {"category": "cars", "age_limit": 10},
        "CARAVAN": {"category": "light_commercial", "age_limit": 10},
        "CIMA": {"category": "cars", "age_limit": 10},
        "CUBE": {"category": "cars", "age_limit": 10},
        "DAYZ": {"category": "cars", "age_limit": 10},
        "DUALIS": {"category": "cars", "age_limit": 10},
        "ELGRAND": {"category": "cars", "age_limit": 10},
        "FRONTIER": {"category": "light_commercial", "age_limit": 6},
        "FUGA": {"category": "cars", "age_limit": 10},
        "JUKE": {"category": "cars", "age_limit": 10},
        "LAFESTA": {"category": "cars", "age_limit": 10},
        "LEAF": {"category": "cars", "age_limit": 10},
        "MARCH": {"category": "cars", "age_limit": 10},
        "MURANO": {"category": "cars", "age_limit": 10},
        "NOTE": {"category": "cars", "age_limit": 10},
        "NV150 AD": {"category": "light_commercial", "age_limit": 10},
        "NV200 VANETTE": {"category": "light_commercial", "age_limit": 10},
        "NV350 CARAVAN": {"category": "light_commercial", "age_limit": 10},
        "PRESAGE": {"category": "cars", "age_limit": 10},
        "PULSAR": {"category": "cars", "age_limit": 10},
        "ROGUE": {"category": "cars", "age_limit": 10},
        "SENTRA": {"category": "cars", "age_limit": 10},
        "SERENA": {"category": "cars", "age_limit": 10},
        "SKYLINE": {"category": "cars", "age_limit": 10},
        "SUNNY": {"category": "cars", "age_limit": 10},
        "TEANA": {"category": "cars", "age_limit": 10},
        "TIIDA": {"category": "cars", "age_limit": 10},
        "TIIDA LATIO": {"category": "cars", "age_limit": 10},
        "VERSA": {"category": "cars", "age_limit": 10},
        "WINGROAD": {"category": "cars", "age_limit": 10},
        "X-TRAIL": {"category": "cars", "age_limit": 10}
    },
    "PEUGEOT": {
        "406": {"category": "cars", "age_limit": 10}
    },
    "PORSCHE": {
        "BOXSTER": {"category": "cars", "age_limit": 10},
        "CAYENNE": {"category": "cars", "age_limit": 10},
        "CAYMAN": {"category": "cars", "age_limit": 10},
        "MACAN": {"category": "cars", "age_limit": 10},
        "PANAMERA": {"category": "cars", "age_limit": 10},
        "TAYCAN": {"category": "cars", "age_limit": 10}
    },
    "SUBARU": {
        "BRZ": {"category": "cars", "age_limit": 10},
        "EXIGA": {"category": "cars", "age_limit": 10},
        "FORESTER": {"category": "cars", "age_limit": 10},
        "IMPREZA": {"category": "cars", "age_limit": 10},
        "IMPREZA G4": {"category": "cars", "age_limit": 10},
        "IMPREZA WRX": {"category": "cars", "age_limit": 10},
        "IMPREZA XV": {"category": "cars", "age_limit": 10},
        "LEGACY": {"category": "cars", "age_limit": 10},
        "LEVORG": {"category": "cars", "age_limit": 10},
        "OUTBACK": {"category": "cars", "age_limit": 10},
        "PLEO": {"category": "cars", "age_limit": 10},
        "WRX STI": {"category": "cars", "age_limit": 10}
    },
    "SUZUKI": {
        "ALTO": {"category": "cars", "age_limit": 10},
        "BALENO": {"category": "cars", "age_limit": 10},
        "EVERY": {"category": "light_commercial", "age_limit": 6},
        "GRAND ESCUDO": {"category": "cars", "age_limit": 10},
        "IGNIS": {"category": "cars", "age_limit": 10},
        "JIMNY": {"category": "cars", "age_limit": 10},
        "SOLIO": {"category": "cars", "age_limit": 10},
        "SWIFT": {"category": "cars", "age_limit": 10},
        "SX4": {"category": "cars", "age_limit": 10},
        "VITARA": {"category": "cars", "age_limit": 10},
        "XL 7": {"category": "cars", "age_limit": 10}
    },
    "TESLA": {
        "MODEL 3": {"category": "cars", "age_limit": 10},
        "MODEL S": {"category": "cars", "age_limit": 10},
        "MODEL X": {"category": "cars", "age_limit": 10},
        "MODEL Y": {"category": "cars", "age_limit": 10}
    },
    "TOYOTA": {
        "4RUNNER": {"category": "cars", "age_limit": 10},
        "86": {"category": "cars", "age_limit": 10},
        "ALLION": {"category": "cars", "age_limit": 10},
        "ALPHARD": {"category": "cars", "age_limit": 10},
        "ALTEZZA": {"category": "cars", "age_limit": 10},
        "AQUA": {"category": "cars", "age_limit": 10},
        "AURIS": {"category": "cars", "age_limit": 10},
        "BB": {"category": "cars", "age_limit": 10},
        "BELTA": {"category": "cars", "age_limit": 10},
        "BLADE": {"category": "cars", "age_limit": 10},
        "C-HR": {"category": "cars", "age_limit": 10},
        "CALDINA": {"category": "cars", "age_limit": 10},
        "CAMRY": {"category": "cars", "age_limit": 10},
        "COASTER": {"category": "commercial", "age_limit": 15},
        "COROLLA": {"category": "cars", "age_limit": 10},
        "COROLLA AXIO": {"category": "cars", "age_limit": 10},
        "COROLLA CROSS": {"category": "cars", "age_limit": 10},
        "COROLLA FIELDER": {"category": "cars", "age_limit": 10},
        "COROLLA RUNX": {"category": "cars", "age_limit": 10},
        "CORSA": {"category": "cars", "age_limit": 10},
        "CROWN": {"category": "cars", "age_limit": 10},
        "CROWN ATHLETE": {"category": "cars", "age_limit": 10},
        "CROWN MAJESTA": {"category": "cars", "age_limit": 10},
        "ESQUIRE": {"category": "cars", "age_limit": 10},
        "ESTIMA": {"category": "cars", "age_limit": 10},
        "FORTUNER": {"category": "cars", "age_limit": 10},
        "HARRIER": {"category": "cars", "age_limit": 10},
        "HIACE": {"category": "light_commercial", "age_limit": 10},
        "HIACE REGIUS": {"category": "light_commercial", "age_limit": 10},
        "HIGHLANDER": {"category": "cars", "age_limit": 10},
        "HILUX PICK UP": {"category": "light_commercial", "age_limit": 6},
        "HILUX SURF": {"category": "cars", "age_limit": 10},
        "IPSUM": {"category": "cars", "age_limit": 10},
        "ISIS": {"category": "cars", "age_limit": 10},
        "KLUGER": {"category": "cars", "age_limit": 10},
        "LAND CRUISER": {"category": "cars", "age_limit": 10},
        "LAND CRUISER PRADO": {"category": "cars", "age_limit": 10},
        "MARK II": {"category": "cars", "age_limit": 10},
        "MARK X": {"category": "cars", "age_limit": 10},
        "MARK X ZIO": {"category": "cars", "age_limit": 10},
        "MATRIX": {"category": "cars", "age_limit": 10},
        "NOAH": {"category": "cars", "age_limit": 10},
        "PASSO": {"category": "cars", "age_limit": 10},
        "PREMIO": {"category": "cars", "age_limit": 10},
        "PRIUS": {"category": "cars", "age_limit": 10},
        "PROBOX": {"category": "light_commercial", "age_limit": 10},
        "RAIZE": {"category": "cars", "age_limit": 10},
        "RAV4": {"category": "cars", "age_limit": 10},
        "RUSH": {"category": "cars", "age_limit": 10},
        "SIENTA": {"category": "cars", "age_limit": 10},
        "SPRINTER": {"category": "cars", "age_limit": 10},
        "STARLET": {"category": "cars", "age_limit": 10},
        "SUCCEED VAN": {"category": "light_commercial", "age_limit": 10},
        "TACOMA": {"category": "light_commercial", "age_limit": 6},
        "TOWN ACE": {"category": "light_commercial", "age_limit": 6},
        "TUNDRA": {"category": "light_commercial", "age_limit": 10},
        "VANGUARD": {"category": "cars", "age_limit": 10},
        "VELLFIRE": {"category": "cars", "age_limit": 10},
        "VITZ": {"category": "cars", "age_limit": 10},
        "VOXY": {"category": "cars", "age_limit": 10},
        "WISH": {"category": "cars", "age_limit": 10},
        "YARIS": {"category": "cars", "age_limit": 10},
        "YARIS CROSS": {"category": "cars", "age_limit": 10}
    },
    "VOLKSWAGEN": {
        "BEETLE": {"category": "cars", "age_limit": 10},
        "GOLF": {"category": "cars", "age_limit": 10},
        "GTI": {"category": "cars", "age_limit": 10},
        "JETTA": {"category": "cars", "age_limit": 10},
        "PASSAT": {"category": "cars", "age_limit": 10},
        "POLO": {"category": "cars", "age_limit": 10},
        "TIGUAN": {"category": "cars", "age_limit": 10}
    },
    "VOLVO": {
        "S40": {"category": "cars", "age_limit": 10},
        "S60": {"category": "cars", "age_limit": 10},
        "S80": {"category": "cars", "age_limit": 10},
        "S90": {"category": "cars", "age_limit": 10},
        "V40": {"category": "cars", "age_limit": 10}
    }
}


